name: Frontend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Stop Existing App
        run: pm2 delete frontend || true

      - name: Start Frontend
        run: pm2 start npm --name frontend -- run dev -- --host 0.0.0.0 --port 5173

      - name: Save PM2 Process
        run: pm2 save
