name: deploy
on: 
  push: 
    branches: 
       - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Ec2
        uses: appleboy/ssh-actions@v1.2.0
        with:
          host: ${{ secrets.IP}}
          username: ubuntu
          key: ${{secrets.PRIVATE_key}}
          script: |
            cd /home/ubuntu/frontseedly
            git pull origin main 
            npm i 
            npm run build 
            sudo npm i pm2 -g
            pm2 restart app || pm2 start npm --name front -- run dev -- --host
          
      
